### ISSUE TITLE
a real bug this time

### ISSUE THREAD

**Issue by master7720** [Supergamer5465/ImpHack-Revised#50]
everytime i go and start the game it crashes

**Comment by Supergamer5465** [comment]
if you go to logs in the minecraft directory (C:\foo\appdata\roaming\.minecraft\logs) you can see it

**Comment by Supergamer5465** [comment]
should be called latest.log

**Comment by Supergamer5465** [comment]
![image](https://user-images.githubusercontent.com/64598162/138619098-03493cbb-dd1f-4118-89a8-2640bc6cf91b.png)
